### ISSUE TITLE
Node.js + Express学習：TypeError: Cannot read property 'db' of null

### ISSUE THREAD

**Issue by seiyan0426** [seiyan0426/todo#4]
62. データベースを準備しよう
TypeError: Cannot read property 'db' of null

$ node ./lib/database/insert-sample.js

(node:858) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option{ useNewUrlParser: true } to MongoClient.connect.

/Users/xxx/Desktop/dev/weblog/node_modules/mongodb/lib/operations/mongo_client_ops.js:462

      throw err;

      ^

TypeError: Cannot read property 'db' of null

    at MongoClient.connect (/Users/xxx/Desktop/dev/weblog/lib/database/insert-sample.js:62:21)

    at err (/Users/xxx/Desktop/dev/weblog/node_modules/mongodb/lib/utils.js:415:14)

    at executeCallback (/Users/xxx/Desktop/dev/weblog/node_modules/mongodb/lib/utils.js:404:25)

    at err (/Users/xxx/Desktop/dev/weblog/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:21)

    at connectCallback (/Users/xxx/Desktop/dev/weblog/node_modules/mongodb/lib/operations/mongo_client_ops.js:240:5)

    at process.nextTick (/Users/xxx/Desktop/dev/weblog/node_modules/mongodb/lib/operations/mongo_client_ops.js:459:7)

    at process._tickCallback (internal/process/next_tick.js:150:11)

insert-sample.js
```js:insert-sample.js
var { CONNECTION_URL, DATABASE, OPTIONS } = require("../../config/mongodb.config");
var MongoClient = require("mongodb").MongoClient;

// posts, users, privileges
var insertPosts = function (db) {
    return Promise.all([
        db.collection("posts").insertMany([{
            url: "/2017/05/hello-nodejs.html",
            published: new Date(2017, 4, 2),
            updated: new Date(2017, 4, 2),
            title: "ようこそ Node.js の世界へ",
            content: "Node.js は おもしろい！",
            keywords: ["Node.js"],
            authors: ["Yuta Sato"]
        }, {
            url: "/2017/06/nodejs-basic.html",
            published: new Date(2017, 5, 12),
            updated: new Date(2017, 5, 12),
            title: "Node.js の 基本",
            content: "ちょっと難しくなってきた！？",
            keywords: ["Node.js"],
            authors: ["Yuta Sato"]
        }, {
            url: "/2017/07/advanced-nodejs.html",
            published: new Date(2017, 7, 8),
            updated: new Date(2017, 7, 8),
            title: "Node.js 応用",
            content: "Node.js で Excel ファイルが触れるなんて！！",
            keywords: ["Node.js"],
            authors: ["Yuta Sato"]
        }]),
        db.collection("posts")
            .createIndex({ url: 1 }, { unique: true, background: true })
    ]);
};

var insertUsers = function (db) {
    return Promise.all([
        db.collection("users").insertOne({
            email: "yuta.sato@sample.com",
            name: "Yuta Sato",
            password: "qwerty", //"qwerty", // "77d1fb804f4e1e6059377122046c95de5e567cb9fd374639cb96e7f5cc07dba1"
            role: "owner"
        }),
        db.collection("users")
            .createIndex({ email: 1 }, { unique: true, background: true })
    ]);
};

var insertPrivileges = function (db) {
    return Promise.all([
        db.collection("privileges").insertMany([
            { role: "default", permissions: ["read"] },
            { role: "owner", permissions: ["readWrite"] }
        ]),
        db.collection("privileges")
            .createIndex({ role: 1 }, { unique: true, background: true })
    ]);
};

MongoClient.connect(CONNECTION_URL, {useNewUrlParser: true}, OPTIONS, (error, client) => {
    var db = client.db(DATABASE);
    Promise.all([
        insertPosts(db),
        insertUsers(db),
        insertPrivileges(db)
    ]).catch((error) => {
        console.log(error);
    }).then(() => {
        client.close();
    });
}); 
```

mongodb.config.js
```js:mongodb.config.js
module.exports = {
    CONNECTION_URL: "mongodb://user:user@localhost:27017/weblog",
    DATABASE: "weblog",
    OPTIONS: {
        family: 4
    }
};
```

**Comment by seiyan0426** [comment]
権限がないため、事前に以下を実施し、再実行することにより、解決。

mongo
use admin
db.auth("admin", "password")
use weblog
db.createUser({
　user: "user",
　pwd: "user",
　roles: [{ role: "readWrite", db: "weblog"}]
})
