### ISSUE TITLE
Node.js + Express学習：記事検索エラー

### ISSUE THREAD

**Issue by seiyan0426** [seiyan0426/todo#5]
タイトルリンク時にエラーとなってしまう。

/usr/local/bin/node --inspect-brk=38852 app.js 
Debugger listening on ws://127.0.0.1:38852/65a0a292-b12d-4912-afd3-063ea67f1f53
Debugger attached.
ReferenceError: /Users/xxx/Desktop/dev/weblog/views/posts/index.ejs:17
    15| 
    16|       <div class="border-bottom mt-5 mb-5">
 >> 17|         <h1><%= title %></h1>
    18|     </div>
    19|     <dl class="row mt-5 mb-5">
    20|         <dt class="col-3">公開日：</dt>
title is not defined
    at eval (eval at compile (/Users/xxx/Desktop/dev/weblog/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:17:26)
    at returnedFn (/Users/xxx/Desktop/dev/weblog/node_modules/ejs/lib/ejs.js:653:17)
    at tryHandleCache (/Users/xxx/Desktop/dev/weblog/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/Users/xxx/Desktop/dev/weblog/node_modules/ejs/lib/ejs.js:482:10)
    at View.render (/Users/xxx/Desktop/dev/weblog/node_modules/express/lib/view.js:135:8)
    at tryRender (/Users/xxx/Desktop/dev/weblog/node_modules/express/lib/application.js:640:10)
    at Function.render (/Users/xxx/Desktop/dev/weblog/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/Users/xxx/Desktop/dev/weblog/node_modules/express/lib/response.js:1008:7)
    at db.collection.findOne.then (/Users/xxx/Desktop/dev/weblog/routes/posts.js:11:17)
    at <anonymous>

**Comment by seiyan0426** [comment]
views/posts/index.ejsにて表示するオブジェクトが呼び出し元から渡されていなかった。
また、呼び出し元の処理もデータベースからデータを取得できておらず、nullだった。
原因は、リンククリック時にurlを生成しているが、正しく生成できておらず、dbへ検索してもデータが取得できなかったためであった。
